### ISSUE TITLE
 PHP Fatal error

### ISSUE THREAD

**Issue by alexzerabr** [AoiKagase/Amxx-PSD#2]
Uncaught RuntimeException: Unable to create the cache directory (templates/compiled/6b). in /var/www/html/csx_stats/vendor/twig/twig/src/Cache/FilesystemCache.php:53\nStack trace:\n#0 /var/www/html/csx_stats/vendor/twig/twig/src/Environment.php(349): Twig\\Cache\\FilesystemCache->write('templates/compi...', '<?php\\n\\nuse Twig...')\n#1 /var/www/html/csx_stats/vendor/twig/twig/src/Environment.php(309): Twig\\Environment->loadTemplate('__TwigTemplate_...', 'index.tpl')\n#2 /var/www/html/csx_stats/vendor/twig/twig/src/Environment.php(277): Twig\\Environment->load('index.tpl')\n#3 /var/www/html/csx_stats/index.php(15): Twig\\Environment->render('index.tpl', Array)\n#4 /var/www/html/csx_stats/includes/page_main.inc(21): Index->select()\n#5 /var/www/html/csx_stats/index.php(33): PageMain->main()\n#6 {main}\n  thrown in /var/www/html/csx_stats/vendor/twig/twig/src/Cache/FilesystemCache.php on line 53

I'm having this error, when opening a php page, I downloaded git

**Comment by alexsanderds** [comment]
how do I display the players' stats, just like their DEMO?

**Comment by alexzerabr** [comment]
Resolvido :-)

**Comment by shakdoesgithub** [comment]
Hey @alexsanderds could you leave a comment on how you resolved it and close the issue ?

**Comment by alexzerabr** [comment]
It was necessary to add permission to the "TEMPLATE" directory
csx_stats / template
chmod 775 / var / www / html / csx_stats / template
